export const GET_CITY_WEATHER = 'GET_CITY_WEATHER';
export const GET_CITY_WEATHER_SUCCESS = 'GET_CITY_WEATHER_SUCCESS';
export const GET_CITY_WEATHER_START = 'GET_CITY_WEATHER_START';
export const GET_CITY_WEATHER_ERROR = 'GET_CITY_WEATHER_ERROR';